// src/constants/categories.js

export const CATEGORY_LIST = [
    "Celulares y Smartphones",
    "Accesorios para Celulares",
    "Computadoras y Notebooks",
    "Televisores y Audio",
    "Videojuegos",
    "Cámaras y Fotografía",
    "Ropa Hombre",
    "Ropa Mujer",
    "Calzado",
    "Muebles",
    "Decoración",
    "Electrodomésticos",
    "Juguetes",
    "Cochecitos y Sillas",
    "Accesorios para Autos",
    "Bicicletas y Accesorios",
    "Libros Físicos",
    "Películas y Series",
    "Maquillaje",
    "Perfumes",
    "Herramientas",
    "Limpieza del Hogar",
    "Regalos y Souvenirs",
    "Papelería",
    "Mascotas",
];

